/*
  Warnings:

  - A unique constraint covering the columns `[biaId]` on the table `Business` will be added. If there are existing duplicate values, this will fail.

*/
-- CreateEnum
CREATE TYPE "Category" AS ENUM ('AGRICULTURE_FORESTRY_FISHING_AND_HUNTING', 'MINING_QUARRYING_OIL_GAS_EXTRACTION', 'UTILITIES', 'CONSTRUCTION', 'MANUFACTURING', 'WHOLESALE_TRADE', 'RETAIL_TRADE', 'TRANSPORTATION_WAREHOUSING', 'INFORMATION_CULTURAL_INDUSTRIES', 'FINANCE_INSURANCE', 'REAL_ESTATE_RENTAL_LEASING', 'PROFESSIONAL_SCIENTIFIC_TECHNICAL_SERVICES', 'MANAGEMENT_COMPANIES_ENTERPRISES', 'ADMINISTRATIVE_SUPPORT_WASTE_MANAGEMENT_REMEDIATION_SERVICES', 'EDUCATIONAL_SERVICES', 'HEALTH_CARE_SOCIAL_ASSISTANCE', 'ARTS_ENTERTAINMENT_RECREATION', 'ACCOMMODATION_FOOD_SERVICES', 'OTHER_SERVICES', 'PUBLIC_ADMINISTRATION');

-- AlterTable
ALTER TABLE "Address" ADD COLUMN     "businessId" TEXT;

-- AlterTable
ALTER TABLE "Business" ADD COLUMN     "Category" "Category" NOT NULL DEFAULT 'OTHER_SERVICES',
ADD COLUMN     "Phone" TEXT,
ADD COLUMN     "biaId" TEXT,
ADD COLUMN     "city" TEXT,
ADD COLUMN     "province" TEXT;

-- CreateIndex
CREATE UNIQUE INDEX "Business_biaId_key" ON "Business"("biaId");

-- AddForeignKey
ALTER TABLE "Business" ADD CONSTRAINT "Business_biaId_fkey" FOREIGN KEY ("biaId") REFERENCES "BIA"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Address" ADD CONSTRAINT "Address_businessId_fkey" FOREIGN KEY ("businessId") REFERENCES "Business"("id") ON DELETE SET NULL ON UPDATE CASCADE;
